---
title: "Reporting"
output: 
  html_document:
    keep_md: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries and data

```{r}
library(magrittr)
library(kableExtra)
library(modelsummary)
library(ggplot2)
dir.create(
  path = here::here("draft/figuretable/tutorial"),
  recursive = TRUE
)
df <- chickwts
```

# Table

## Table by kableExtra


```{r}
# make summary table
table_summary <-
  df %>%
  dplyr::group_by(feed) %>%
  dplyr::summarise(
    N = length(weight),
    mean = mean(weight),
    sd = sd(weight),
    min = min(weight),
    median = median(weight),
    max = max(weight),
    .groups = "drop"
  ) %>%
  dplyr::ungroup() 

# export to html for display
table_summary %>%
  kbl() %>%
  kable_classic()

# export to latex for draft
table_summary%>%
  kbl(
    format = "latex",
    booktabs = TRUE
  ) %>%
  save_kable(
    file = here::here("draft/figuretable/tutorial/table_kable.tex")
  )
```
## Regression table by modelsummary

```{r}
# run a regression
table_regression <-
  df %>%
  lfe::felm(
    data = .,
    formula = weight ~ as.factor(feed)
  )

# export to html for display
table_regression %>%
  modelsummary(
    models = .,
    stars = TRUE
  ) %>%
  kable_classic()

# export to latex for draft
table_regression %>%
  modelsummary(
    models = .,
    stars = TRUE,
    booktabs = TRUE,
    output = "latex_tabular"
  ) %>%
  gsub("\\multicolumn.*\\\\", "", .) %>%
  save_kable(
    file = here::here("draft/figuretable/tutorial/table_modelsummary.tex")
    )
```

# Figure

## Bar plot by ggplot2

```{r}
# display plot
df %>%
  dplyr::group_by(feed) %>%
  dplyr::summarise(
    mean = mean(weight),
    .groups = "drop"
  ) %>%
  dplyr::mutate(group = "all") %>%
  ggplot(
    aes(
      x = feed,
      y = mean,
      fill = group
    )
  ) +
  geom_bar(
    stat = "identity"
    ) +
  labs(
    x = "Feed",
    y = "Weight (g)"
  ) +
  scale_fill_viridis_d() +
  theme_classic() +
  theme(
    legend.position = "none"
  )
# save
ggsave(
  filename = here::here("draft/figuretable/tutorial/figure_bar_ggplot2.png"),
  width = 4,
  height = 3
)
```

## Error bar plot by ggplot2

```{r}
# display plot
df %>%
  dplyr::group_by(feed) %>%
  dplyr::summarise(
    mean = mean(weight),
    upper = mean(weight) + sd(weight),
    lower = mean(weight) - sd(weight),
    .groups = "drop"
  ) %>%
  dplyr::mutate(group = "all") %>%
  ggplot(
    aes(
      x = feed,
      y = mean,
      fill = group
    )
  ) +
  geom_bar(
    stat = "identity"
    ) +
  geom_errorbar(
    aes(
      x = feed,
      ymin = lower,
      ymax = upper
    ),
    width = 0.5
  ) +
  scale_fill_viridis_d() +
  theme_classic() +
  theme(
    legend.position = "none"
  )
# save
ggsave(
  filename = here::here("draft/figuretable/tutorial/figure_errorbar_ggplot2.png"),
  width = 4,
  height = 3
)
```

